export const BulgariaRoutes = {
  "Indonesia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Steer Med 3",
    "Steer Suez Exit",
    "Steer Suez Canal",
    "Steer Red Sea 3",
    "Steer Red Sea 2",
    "Steer Red Sea 1",
    "Steer Red Sea Entry",
    "Steer Bab el Mandeb",
    "Yemen",
    "Steer Socotra",
    "Steer Oman South",
    "Steer Oman Central",
    "Steer Oman East",
    "Steer Muscat Coast",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta"
  ],
  "Yunani": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Rumania": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Bulgaria",
    "Steer Bosphorus",
    "Turki",
    "Yunani",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const BulgariaWaypoints = { "Bulgaria": { "lon": 27.91, "lat": 43.21 } };
