export const IslandiaRoutes = {
  "Greenland": [
    "Islandia",
    "Greenland"
  ],
  "Greenlandia": [
    "Islandia",
    "Greenland"
  ],
  "Indonesia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Steer Med 3",
    "Steer Suez Exit",
    "Steer Suez Canal",
    "Steer Red Sea 3",
    "Steer Red Sea 2",
    "Steer Red Sea 1",
    "Steer Red Sea Entry",
    "Steer Bab el Mandeb",
    "Yemen",
    "Steer Socotra",
    "Steer Oman South",
    "Steer Oman Central",
    "Steer Oman East",
    "Steer Muscat Coast",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta"
  ],
  "Yunani": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Kroasia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Islandia",
    "Steer North Atlantic",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const IslandiaWaypoints = { "Islandia": { "lon": -21.94, "lat": 64.14 } };
