export const NorwegiaRoutes = {
  "Indonesia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Steer Med 3",
    "Steer Suez Exit",
    "Steer Suez Canal",
    "Steer Red Sea 3",
    "Steer Red Sea 2",
    "Steer Red Sea 1",
    "Steer Red Sea Entry",
    "Steer Bab el Mandeb",
    "Yemen",
    "Steer Socotra",
    "Steer Oman South",
    "Steer Oman Central",
    "Steer Oman East",
    "Steer Muscat Coast",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta"
  ],
  "Yunani": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Irlandia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Norwegia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Albania"
  ],
  "Greenland": [
    "Norwegia",
    "Steer Iceland North",
    "Steer Greenland Upper",
    "Steer Canada Arctic",
    "Steer Baffin Bay",
    "Greenland"
  ]
};

export const NorwegiaWaypoints = { "Norwegia": { "lon": 10.75, "lat": 59.91 } };
