export const SwediaRoutes = {
  "Indonesia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Steer Med 3",
    "Steer Suez Exit",
    "Steer Suez Canal",
    "Steer Red Sea 3",
    "Steer Red Sea 2",
    "Steer Red Sea 1",
    "Steer Red Sea Entry",
    "Steer Bab el Mandeb",
    "Yemen",
    "Steer Socotra",
    "Steer Oman South",
    "Steer Oman Central",
    "Steer Oman East",
    "Steer Muscat Coast",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta"
  ],
  "Yunani": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Norwegia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Swedia",
    "Denmark",
    "Jerman",
    "Belanda",
    "Belgia",
    "Inggris",
    "Steer Biscay",
    "Steer Gibraltar",
    "Portugal",
    "Spanyol",
    "Prancis",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const SwediaWaypoints = { "Swedia": { "lon": 18.06, "lat": 59.32 } };
