export const AustraliaRoutes = {
  "Japan": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Brunei": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia (Alternatif)": [
    "Australia",
    "Steer Brisbane",
    "Steer Coral Sea",
    "Steer Cape York",
    "Steer Arafura",
    "Steer Banda Sea",
    "Steer Flores Sea",
    "Laut Jawa",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ]
};

export const AustraliaWaypoints = {
  "Australia": {
    "lon": 151.0,
    "lat": -33.8
  }
};
