export const BangladeshRoutes = {
  "Japan": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Sri Lanka": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const BangladeshWaypoints = {
  "Bangladesh": {
    "lon": 91,
    "lat": 22.6
  }
};
