export const BangladeshRoutes = {
  "Japan": [
    "Bangladesh",
    "Steer Bay 3",
    "Myanmar",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "Indonesia": [
    "Bangladesh",
    "Steer Bay 3",
    "Myanmar",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Malaysia",
    "Singapore",
    "Jakarta"
  ],
  "Sri Lanka": [
    "Bangladesh",
    "Steer Bay 3",
    "Myanmar",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka"
  ],
  "North Korea": [
    "Bangladesh",
    "Steer Bay 3",
    "Myanmar",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ]
};

export const BangladeshWaypoints = {
  "Bangladesh": {
    "lon": 91,
    "lat": 22.6
  }
};
