export const IndonesiaRoutes = {
  "Japan": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ]
};

export const IndonesiaWaypoints = {
  "Jakarta": {
    "lon": 106.8,
    "lat": -6.2
  },
  "Aceh": {
    "lon": 95,
    "lat": 7.5
  }
};
