export const JapanRoutes = {
  "Pakistan": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Iran": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Iran"
  ],
  "Bangladesh": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar",
    "Steer Bay 3",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka"
  ],
  "Indonesia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta"
  ]
};

export const JapanWaypoints = {
  "Japan": {
    "lon": 140,
    "lat": 35.2
  }
};
