export const JapanRoutes = {
  "South Korea": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Japan",
    "Approach Japan",
    "Steer Japan 2",
    "Steer Japan",
    "Steer Kyushu",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const JapanWaypoints = {
  "Japan": {
    "lon": 140,
    "lat": 35.2
  }
};
