export const KuwaitRoutes = {
  "Japan": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Yemen": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Kuwait",
    "Steer Kuwait",
    "Bahrain",
    "Steer Qatar North",
    "Qatar",
    "United Arab Emirates",
    "Iran",
    "Steer Hormuz",
    "Steer Musandam",
    "Steer Gulf of Oman",
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const KuwaitWaypoints = {
  "Kuwait": {
    "lon": 48,
    "lat": 29.4
  }
};
