export const NorthKoreaRoutes = {
  "China": [
    "North Korea",
    "Steer Yellow Sea",
    "China"
  ],
  "Pakistan": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Iran": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Iran"
  ],
  "Bangladesh": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Selat Malaka",
    "Steer Andaman",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar",
    "Steer Bay 3",
    "Bangladesh",
    "Steer Bay 3",
    "Steer Bay 2",
    "Steer Bay 1",
    "Palk East Exit",
    "Palk Strait",
    "Palk West Entry",
    "Sri Lanka"
  ],
  "Indonesia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta"
  ]
};

export const NorthKoreaWaypoints = {
  "North Korea": {
    "lon": 125,
    "lat": 38.6
  }
};
