export const NorthKoreaRoutes = {
  "Japan": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "Myanmar": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "North Korea",
    "Steer Yellow Sea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const NorthKoreaWaypoints = {
  "North Korea": {
    "lon": 125,
    "lat": 38.6
  }
};
