export const OmanRoutes = {
  "Japan": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "South Korea": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea"
  ],
  "North Korea": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Iran": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "Oman",
    "Steer Makran",
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const OmanWaypoints = {
  "Oman": {
    "lon": 58.6,
    "lat": 23.6
  }
};
