export const PakistanRoutes = {
  "Japan": [
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh",
    "Steer Andaman",
    "Selat Malaka",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "North Korea": [
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh",
    "Steer Andaman",
    "Selat Malaka",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Indonesia": [
    "Pakistan",
    "Steer Gujarat",
    "India",
    "Steer Arabian Sea",
    "Steer Sri Lanka West",
    "Sri Lanka",
    "Steer Sri Lanka SW",
    "Steer Sri Lanka South",
    "Aceh",
    "Selat Malaka",
    "Singapore",
    "Jakarta"
  ]
};

export const PakistanWaypoints = {
  "Pakistan": {
    "lon": 67,
    "lat": 24.8
  }
};
