export const SouthKoreaRoutes = {
  "Japan": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Approach Korea",
    "South Korea",
    "Approach Korea",
    "Steer Kyushu",
    "Steer Japan",
    "Steer Japan 2",
    "Approach Japan",
    "Japan"
  ],
  "North Korea": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China",
    "Steer Yellow Sea",
    "North Korea"
  ],
  "Myanmar": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Myanmar"
  ],
  "China": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand",
    "Steer Gulf",
    "Kamboja",
    "Steer SCS South",
    "Steer SCS East",
    "Vietnam",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan",
    "China"
  ],
  "Taiwan": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina",
    "Taiwan"
  ],
  "Filipina": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Brunei",
    "Brunei",
    "Filipina"
  ],
  "Singapore": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore"
  ],
  "Bangladesh": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Palk West Entry",
    "Palk Strait",
    "Palk East Exit",
    "Steer Bay 1",
    "Steer Bay 2",
    "Steer Bay 3",
    "Bangladesh"
  ],
  "Sri Lanka": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka"
  ],
  "India": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India"
  ],
  "Pakistan": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan"
  ],
  "Oman": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman"
  ],
  "Iran": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran"
  ],
  "United Arab Emirates": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates"
  ],
  "Qatar": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar"
  ],
  "Bahrain": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain"
  ],
  "Kuwait": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Gulf of Oman",
    "Steer Musandam",
    "Steer Hormuz",
    "Iran",
    "United Arab Emirates",
    "Qatar",
    "Steer Qatar North",
    "Bahrain",
    "Steer Kuwait",
    "Kuwait"
  ],
  "Yemen": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen"
  ],
  "Saudi Arabia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Saudi Arabia"
  ],
  "Italia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia"
  ],
  "Brunei": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Steer Brunei",
    "Brunei"
  ],
  "Malaysia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia"
  ],
  "Vietnam": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Vietnam"
  ],
  "Thailand": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Thailand"
  ],
  "Kamboja": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Malaysia",
    "Singapore",
    "Steer Johor",
    "Kamboja"
  ],
  "Australia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Laut Jawa",
    "Steer Flores Sea",
    "Steer Banda Sea",
    "Steer Arafura",
    "Steer Cape York",
    "Steer Coral Sea",
    "Steer Brisbane",
    "Australia"
  ],
  "Australia (Alternatif)": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Selat Sunda",
    "Steer Samudra Hindia",
    "Steer Bight",
    "Australia"
  ],
  "Yunani": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani"
  ],
  "Turki": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki"
  ],
  "Bulgaria": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria"
  ],
  "Rumania": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania"
  ],
  "Ukraina": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Turki",
    "Steer Bosphorus",
    "Bulgaria",
    "Rumania",
    "Ukraina"
  ],
  "Prancis": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis"
  ],
  "Spanyol": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol"
  ],
  "Portugal": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal"
  ],
  "Inggris": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris"
  ],
  "Belgia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia"
  ],
  "Belanda": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda"
  ],
  "Jerman": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman"
  ],
  "Denmark": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark"
  ],
  "Poland": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland"
  ],
  "Latvia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia"
  ],
  "Estonia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia"
  ],
  "Finlandia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Latvia",
    "Estonia",
    "Finlandia"
  ],
  "Lithuania": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Poland",
    "Lithuania"
  ],
  "Swedia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Swedia"
  ],
  "Norwegia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Inggris",
    "Belgia",
    "Belanda",
    "Jerman",
    "Denmark",
    "Norwegia"
  ],
  "Irlandia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Irlandia"
  ],
  "Islandia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Prancis",
    "Spanyol",
    "Portugal",
    "Steer Gibraltar",
    "Steer Biscay",
    "Steer North Atlantic",
    "Islandia"
  ],
  "Kroasia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia"
  ],
  "Montenegro": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Montenegro"
  ],
  "Slovenia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Slovenia"
  ],
  "Bosnia": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Kroasia",
    "Bosnia"
  ],
  "Albania": [
    "South Korea",
    "Approach Korea",
    "China",
    "Taiwan",
    "Filipina",
    "Brunei",
    "Steer Brunei",
    "Vietnam",
    "Steer SCS East",
    "Steer SCS South",
    "Kamboja",
    "Steer Gulf",
    "Thailand",
    "Steer Johor",
    "Singapore",
    "Malaysia",
    "Jakarta",
    "Singapore",
    "Selat Malaka",
    "Aceh",
    "Steer Sri Lanka South",
    "Steer Sri Lanka SW",
    "Sri Lanka",
    "Steer Sri Lanka West",
    "Steer Arabian Sea",
    "India",
    "Steer Gujarat",
    "Pakistan",
    "Steer Makran",
    "Oman",
    "Steer Muscat Coast",
    "Steer Oman East",
    "Steer Oman Central",
    "Steer Oman South",
    "Steer Socotra",
    "Yemen",
    "Steer Bab el Mandeb",
    "Steer Red Sea Entry",
    "Steer Red Sea 1",
    "Steer Red Sea 2",
    "Steer Red Sea 3",
    "Steer Suez Canal",
    "Steer Suez Exit",
    "Steer Med 3",
    "Italia",
    "Yunani",
    "Albania"
  ]
};

export const SouthKoreaWaypoints = {
  "South Korea": {
    "lon": 129.3,
    "lat": 35
  }
};
