/**
 * AUTO-GENERATED WORLD RIVALRIES DATA
 * Do not edit this file directly. Edit the .txt files in data_rivalitas_parts/
 */

export const GEOPOLITICAL_DATABASE = {
    "info_utama": [],
    "blok_barat___nato": [
        "[BLOK BARAT / NATO]",
        "Negara Utama: Amerika Serikat, Inggris, Perancis, Jerman, Italia, Kanada.",
        "Sikap Dasar: ",
        "- Sangat Akrab (+80 - +100) sesama anggota.",
        "- Musuh Bebuyutan (-50 - -100) dengan Rusia dan Korea Utara.",
        "- Rival Strategis (-20 - -50) dengan China dan Iran."
    ],
    "blok_timur___brics_": [
        "[BLOK TIMUR / BRICS+]",
        "Negara Utama: Rusia, China, India, Brazil, Afrika Selatan, Iran.",
        "Sikap Dasar:",
        "- Akrab (+50 - +80) antara Rusia, China, dan Iran.",
        "- Kompetisi Internal (Netral) antara China dan India (Masalah Perbatasan)."
    ],
    "persahabatan_strategis__special_allies_": [
        "[PERSAHABATAN STRATEGIS (SPECIAL ALLIES)]",
        "- AS & Inggris / Israel: +95 (Dukungan Mutlak).",
        "- Rusia & Belarus: +98 (Aliansi Total).",
        "- China & Pakistan: +90 (Iron Brothers).",
        "- Indonesia & Malaysia / Singapura: +60 (Mitra Regional).",
        "- Australia & AS / Inggris: +90 (AUKUS Partnership)."
    ],
    "titik_keteganan_dunia__hotspots_": [
        "[TITIK KETEGANAN DUNIA (HOTSPOTS)]",
        "1. Semenanjung Korea:",
        "   - Korea Utara vs Korea Selatan: -95 (Permusuhan Total).",
        "   - Korea Utara vs Jepang/AS: -90.",
        "2. Timur Tengah:",
        "   - Iran vs Arab Saudi: -40 (Persaingan Regional).",
        "   - Israel vs Palestina/Iran: -98.",
        "3. Eropa Timur:",
        "   - Rusia vs Ukraina: -100.",
        "   - Rusia vs Polandia/Baltik: -60.",
        "4. Indo-Pasifik:",
        "   - China vs Taiwan: -90.",
        "   - China vs India: -30.",
        "   - China vs Filipina/Vietnam: -45 (Sengketa Laut China Selatan).",
        "5. Asia Selatan:",
        "   - India vs Pakistan: -95 (Konflik Nuklir Kashmir).",
        "6. Kaukasus & Balkan:",
        "   - Armenia vs Azerbaijan: -95.",
        "   - Serbia vs Kosovo: -90.",
        "7. Afrika & Amerika Latin:",
        "   - Mesir vs Ethiopia: -50 (Sengketa Sungai Nil).",
        "   - Venezuela vs Guyana: -40 (Sengketa Wilayah Essequibo).",
        "   - AS vs Kuba/Venezuela/Nikaragua: -60 (Blok Sosialis Anti-Barat).",
        "8. Sengketa Kepulauan & Sejarah:",
        "   - Inggris vs Argentina: -45 (Sengketa Falkland/Malvinas).",
        "   - Jepang vs Rusia: -40 (Sengketa Kepulauan Kuril).",
        "   - Turki vs Yunani: -55 (Sengketa Laut Mediterania).",
        "9. Ketegangan Baru (Sahel & Afrika Barat):",
        "   - Mali/Niger/Burkina Faso vs Perancis: -70 (Sentimen Anti-Eropa)."
    ],
    "logika_veto___perlindungan_sekutu__unsc_p5_": [
        "[LOGIKA VETO & PERLINDUNGAN SEKUTU (UNSC P5)]",
        "1. Veto Amerika Serikat: Melindungi Israel dari semua resolusi sanksi.",
        "2. Veto Rusia: Melindungi Belarusia, Suriah, dan Iran.",
        "3. Veto China: Melindungi Korea Utara dan Pakistan.",
        "4. Veto Inggris/Perancis: Melindungi kepentingan Uni Eropa & NATO."
    ],
    "geopolitik_sumber_daya___ekonomi__economic_weaponry_": [
        "[GEOPOLITIK SUMBER DAYA & EKONOMI (ECONOMIC WEAPONRY)]",
        "1. Monopoli Mineral Kritis: China (Mempengaruhi biaya industri global).",
        "2. Kartel Minyak (OPEC+): Arab Saudi & Rusia (Mempengaruhi inflasi/anggaran).",
        "3. Jalur Perdagangan Kritis: Terusan Suez (Mesir), Selat Malaka (Indonesia/Malaysia), Selat Hormuz (Iran)."
    ],
    "logika_krisis___panik_global__systemic_effects_": [
        "[LOGIKA KRISIS & PANIK GLOBAL (SYSTEMIC EFFECTS)]",
        "1. Krisis Semikonduktor: Jika Taiwan (Hotspot) dalam status Perang, Pendapatan Industri Teknologi Global -80%.",
        "2. Penjera Nuklir (P5): Negara P5 tidak bisa saling menyerang secara langsung (Tombol serang terkunci jika lawan adalah P5).",
        "3. Krisis Pengungsi: Perang di satu wilayah akan menurunkan Kepuasan Rakyat negara tetangga sebesar 15%."
    ],
    "persaingan_masa_depan__future_frontiers_": [
        "[PERSAINGAN MASA DEPAN (FUTURE FRONTIERS)]",
        "1. Perang Arktik: Rusia vs NATO (Perebutan minyak & jalur laut kutub).",
        "2. Space Race 2.0: AS vs China (Persaingan pangkalan di Bulan & Mars).",
        "3. Perang Siber: Serangan anonim yang merusak infrastruktur (AI Triggered)."
    ],
    "kekuatan_tengah___blok_regional__regional_power_": [
        "[KEKUATAN TENGAH & BLOK REGIONAL (REGIONAL POWER)]",
        "1. Gerakan Non-Blok (Indonesia/India/Brazil): Menyeimbangkan pengaruh AS-China.",
        "2. Uni Eropa (EU): Solidaritas ekonomi total jika anggota diserang.",
        "3. ASEAN: Zona damai & netral (Sulit diprovokasi untuk perang).",
        "4. Liga Arab / Uni Afrika: Solidaritas regional berdasarkan identitas & geografi."
    ],
    "tipe_kepribadian_negara_ai__ai_personalities_": [
        "[TIPE KEPRIBADIAN NEGARA AI (AI PERSONALITIES)]",
        "1. Interventionist (AS/Perancis): Aktif mencampuri urusan global.",
        "2. Expansionist (Rusia/China/Turki): Fokus pada perluasan pengaruh/wilayah.",
        "3. Isolationist (Korea Utara/Turkmenistan): Tertutup & sulit berdiplomasi.",
        "4. Pacifist (Swiss/Jepang): Menghindari konflik & fokus pada ekonomi."
    ],
    "profil_geopolitik_negara_spesifik__nation_specific_logic_": [
        "[PROFIL GEOPOLITIK NEGARA SPESIFIK (NATION SPECIFIC LOGIC)]",
        "1. India: Penyeimbang global (Rival China, mitra senjata Rusia, mitra teknologi AS).",
        "2. Jepang & Korsel: Perisai teknologi AS (Sangat sensitif terhadap ancaman Korut & China).",
        "3. Turki: Kekuatan penengah (NATO yang fleksibel, eksportir teknologi Drone).",
        "4. Iran: Strategi Proksi (Menggunakan jaringan milisi untuk pengaruh regional).",
        "5. Arab Saudi: Hegemoni Energi & Islam (Rivalitas dengan Iran, transisi ke ekonomi Vision 2030).",
        "6. Brazil: Pemimpin Amerika Latin (Raksasa pangan & lobi lingkungan global).",
        "7. Australia: Jangkar Pasifik (Vokal melawan China, fokus pada aliansi AUKUS).",
        "8. Pakistan: Sekutu besi China (Fokus utama adalah rivalitas dengan India).",
        "9. Israel: Dominasi Intelijen & Teknologi Militer (Fokus pada ancaman eksistensial Iran).",
        "10. Vietnam & Filipina: Penjaga Laut China Selatan (Garda depan melawan klaim China).",
        "11. Jerman: Mesin ekonomi EU (Pasifis militer, fokus pada sanksi & stabilitas ekonomi).",
        "12. Perancis: Otonomi Strategis (Kekuatan nuklir Eropa, aktif di Afrika & Pasifik).",
        "13. Inggris: Global Britain (Sekutu militer inti AS, fokus pada keuangan & intelijen).",
        "14. Mesir: Penjaga Suez (Mediator konflik Arab-Israel, kunci stabilitas logistik dunia).",
        "15. Singapura: Hub Netral (Logistik & Keuangan global, penyeimbang AS-China).",
        "16. Afrika Selatan & Nigeria: Raksasa Afrika (Suara Global South, fokus pada stabilitas benua).",
        "17. Ukraina: Benteng Timur (Titik benturan total blok Barat vs Timur).",
        "18. Taiwan: Jantung Semikonduktor (Titik paling krusial dalam perang teknologi global).",
        "19. Polandia: Bastion NATO Timur (Sangat vokal melawan Rusia, kekuatan militer baru Eropa).",
        "20. Mexico: Pintu Gerbang Amerika (Kunci perdagangan & migrasi ke Amerika Utara).",
        "21. Kanada: Penjaga Arktik (Fokus pada multilateralisme & keamanan kutub utara).",
        "22. Norwegia: Pemasok Energi Eropa (Kaya minyak/gas, aktif dalam diplomasi perdamaian).",
        "23. Swiss: Vault Finansial (Netralitas absolut, hub diplomasi & keuangan dunia).",
        "24. Qatar: Mediator Teluk (Eksportir LNG, jembatan diplomasi kelompok ekstrem & Barat).",
        "25. Malaysia: Hub Manufaktur & Halal (Pemain kunci chip, diplomasi netralitas aktif).",
        "26. Thailand: Diplomasi Bambu (Lincah menyeimbangkan aliansi militer AS & ekonomi China).",
        "27. Venezuela: Pemberontak Energi (Anti-Barat, sekutu erat Rusia-China-Iran).",
        "28. Kolombia: Mitra Utama AS di Amerika Latin (Fokus pada perang narkoba & stabilitas).",
        "29. Ethiopia: Raksasa Tanduk Afrika (Fokus pada kedaulatan air Nil & pengaruh regional).",
        "30. Argentina: Kekuatan Pertanian (Sering mengalami krisis ekonomi, fokus pada pemulihan & BRICS).",
        "31. Kazakhstan: Jembatan Asia Tengah (Penyeimbang pengaruh Rusia, China, & Barat).",
        "32. Swedia & Finlandia: Sentinel Baltik (Kekuatan teknologi siber & anggota baru NATO).",
        "33. Irak: Medan Diplomasi (Menyeimbangkan pengaruh antara AS & Iran di Timur Tengah).",
        "34. Yunani: Kekuatan Maritim Mediterania (Rivalitas laut dengan Turki, kunci gerbang migrasi).",
        "35. Hungaria: Pemain Outlier (Anggota EU/NATO yang pro-bisnis dengan Rusia & China).",
        "36. Kenya: Hub Teknologi Afrika (Pusat inovasi Afrika Timur & sekutu keamanan AS).",
        "37. Chile: Raja Tembaga (Ekonomi stabil Amerika Latin, eksportir mineral kunci).",
        "38. Ukraina: Garis Depan (Bertahan dari invasi, magnet bantuan militer Barat).",
        "39. Filipina: Penjaga Pasifik Barat (Fokus pada sengketa laut & aliansi militer dengan AS).",
        "40. Uni Emirat Arab: Hub Finansial Arab (Modernisasi cepat, diplomasi netralitas aktif)."
    ],
    "daftar_rivalitas_abadi__eternal_rivalries_-_natural_drift_down_": [
        "[DAFTAR RIVALITAS ABADI (ETERNAL RIVALRIES - NATURAL DRIFT DOWN)]",
        "1. AS vs Rusia: Persaingan hegemoni global.",
        "2. AS vs China: Perang dagang & supremasi teknologi.",
        "3. India vs Pakistan: Sengketa wilayah Kashmir & agama.",
        "4. Arab Saudi vs Iran: Perebutan pengaruh di dunia Islam & Timur Tengah.",
        "5. Israel vs Iran: Ancaman eksistensial & perang proksi.",
        "6. Korut vs Korsel: Ideologi & sengketa semenanjung.",
        "7. China vs Taiwan: Kedaulatan & integritas wilayah.",
        "8. Rusia vs Ukraina: Kedaulatan & perluasan NATO.",
        "9. Turki vs Yunani: Sengketa wilayah laut & sejarah.",
        "10. Ethiopia vs Mesir: Perebutan sumber daya air Sungai Nil.",
        "11. Maroko vs Aljazair: Sengketa wilayah Sahara Barat.",
        "12. Armenia vs Azerbaijan: Sengketa wilayah Nagorno-Karabakh."
    ],
    "daftar_aliansi_besi__ironclad_alliances_-_natural_drift_up_": [
        "[DAFTAR ALIANSI BESI (IRONCLAD ALLIANCES - NATURAL DRIFT UP)]",
        "1. AS - Inggris: Hubungan spesial & intelijen (Five Eyes).",
        "2. AS - Israel: Aliansi keamanan & teknologi militer tingkat tinggi.",
        "3. Rusia - Belarusia: Persatuan ekonomi & militer total.",
        "4. China - Pakistan: Sekutu strategis melawan India.",
        "5. China - Korut: Penjaga stabilitas komunis di Asia Timur.",
        "6. Arab Saudi - UEA: Solidaritas monarki Arab & ekonomi.",
        "7. Australia - Selandia Baru: Aliansi Pasifik & sejarah (ANZAC).",
        "8. Perancis - Jerman: Motor penggerak Uni Eropa."
    ],
    "daftar_blok_strategis__strategic___economic_blocs_": [
        "[DAFTAR BLOK STRATEGIS (STRATEGIC & ECONOMIC BLOCS)]",
        "1. NATO (Keamanan Barat): AS, Inggris, Perancis, Jerman, Polandia, dll (Solidaritas militer total).",
        "2. BRICS+ (Ekonomi Baru): China, Rusia, India, Brazil, Afsel, Iran, Arab Saudi, dll (Alternatif sistem Barat).",
        "3. ASEAN (Asia Tenggara): Indonesia, Malaysia, Singapura, Thailand, dll (Zona damai & netral).",
        "4. Uni Eropa / EU (Integrasi Eropa): Jerman, Perancis, Italia, Spanyol, dll (Pasar tunggal & kebijakan sanksi bersama).",
        "5. AUKUS (Pasifik): AS, Inggris, Australia (Aliansi kapal selam nuklir & teknologi canggih).",
        "6. CSTO (Blok Rusia): Rusia, Belarusia, Kazakhstan, Armenia, dll (Pertahanan bersama pasca-Soviet).",
        "7. GCC (Dewan Teluk): Arab Saudi, UEA, Qatar, Kuwait, dll (Aliansi energi & ekonomi Arab).",
        "8. QUAD (Indo-Pasifik): AS, Jepang, India, Australia (Membendung pengaruh China di laut).",
        "9. G7 (Negara Maju): AS, Jepang, Jerman, Inggris, Perancis, Italia, Kanada (Penentu aturan keuangan global).",
        "10. OIC / OKI (Dunia Islam): Arab Saudi, Indonesia, Pakistan, Iran, dll (Solidaritas isu umat Islam)."
    ],
    "daftar_negara_titik_benturan__flashpoint___proxy_nations_": [
        "[DAFTAR NEGARA TITIK BENTURAN (FLASHPOINT & PROXY NATIONS)]",
        "1. Taiwan: Titik benturan paling berbahaya AS vs China (Kedaulatan & Chip).",
        "2. Ukraina: Garis depan benturan NATO vs Rusia (Keamanan Eropa).",
        "3. Suriah & Yaman: Medan proksi utama di Timur Tengah (Iran vs Saudi vs Rusia vs AS).",
        "4. Belarusia: Benteng terakhir Rusia di Eropa Timur (Buffer Rusia vs NATO).",
        "5. Myanmar: Krisis internal ASEAN (Medan pengaruh China vs Barat).",
        "6. Moldova & Georgia: Target perluasan pengaruh EU vs Rusia.",
        "7. Libya: Perebutan sumber daya energi & kendali migrasi (Turki vs Rusia vs EU).",
        "8. Kosovo & Serbia: Titik api sengketa etnis & sejarah di Balkan (EU vs Rusia).",
        "9. Azerbaijan & Armenia: Sengketa wilayah Kaukasus (Turki vs Rusia).",
        "10. Guyana: Sengketa minyak baru (Venezuela vs AS)."
    ],
    "daftar_raja_sumber_daya__resource_kings_-_global_leverage_": [
        "[DAFTAR RAJA SUMBER DAYA (RESOURCE KINGS - GLOBAL LEVERAGE)]",
        "1. Raja Chip (Semikonduktor): Taiwan & Korea Selatan (Ketergantungan teknologi global).",
        "2. Raja Lithium & Cobalt: Chile, Australia, & RD Kongo (Kunci transisi energi hijau).",
        "3. Raja Gas Alam: Rusia, Qatar, & AS (Kontrol pemanas & listrik dunia).",
        "4. Raja Minyak: Arab Saudi, AS, Rusia, Irak, & Iran (Kontrol harga BBM dunia).",
        "5. Raja Gandum & Pupuk: Rusia, Ukraina, Kanada, & AS (Kontrol stabilitas pangan).",
        "6. Raja Tembaga: Chile & Peru (Kunci infrastruktur listrik & bangunan).",
        "7. Raja Mineral Langka (Rare Earths): China (Kontrol komponen militer & gadget canggih).",
        "8. Raja Nikel: Indonesia (Kontrol rantai pasok baterai dunia).",
        "9. Raja Keuangan (USD): Amerika Serikat (Kontrol transaksi perbankan global).",
        "10. Raja Manufaktur: China (Pabrik dunia untuk segala jenis barang)."
    ],
    "daftar_kekuatan_nuklir__nuclear_deterrence_": [
        "[DAFTAR KEKUATAN NUKLIR (NUCLEAR DETERRENCE)]",
        "1. P5 (Resmi): AS, Rusia, China, Inggris, Perancis (Pemegang mandat keamanan PBB).",
        "2. De Facto (Non-PBB): India & Pakistan (Rivalitas nuklir aktif).",
        "3. Undisclosed (Rahasia): Israel (Deterrence utama di Timur Tengah).",
        "4. Wildcard (Ancaman): Korea Utara (Sering menggunakan uji coba nuklir sebagai lobi).",
        "5. Threshold States (Potensial): Iran & Jepang (Mampu membangun nuklir dalam hitungan bulan jika status keamanan kritis)."
    ],
    "daftar_dinamika_identitas___agama__identity_politics_": [
        "[DAFTAR DINAMIKA IDENTITAS & AGAMA (IDENTITY POLITICS)]",
        "1. Rivalitas Sunni vs Syiah: Arab Saudi vs Iran (Mempengaruhi seluruh Timur Tengah).",
        "2. Solidaritas Dunia Islam: Isu Palestina (Mempengaruhi hubungan OKI vs Israel/Barat).",
        "3. Benturan Nilai Barat vs Konservatif: Isu hak asasi & kebebasan vs nilai tradisional (Rusia/Timur Tengah vs EU/AS).",
        "4. Gerakan Separatisme Dunia: Kurdi (Turki/Irak), Tibet & Xinjiang (China), Papua (Indonesia), Catalonia (Spanyol).",
        "5. Sejarah Luka Perang: Jepang vs China/Korea (Sentimen masa lalu yang menghambat kerjasama penuh).",
        "6. Identitas Slavia: Rusia & Belarusia vs Ukraina & Polandia (Persaudaraan etnis yang terpecah ideologi)."
    ],
    "jaringan_intelijen___bantuan_strategis__shadow_diplomacy_": [
        "[JARINGAN INTELIJEN & BANTUAN STRATEGIS (SHADOW DIPLOMACY)]",
        "1. Aliansi Intelijen Five Eyes: AS, Inggris, Kanada, Australia, NZ (Berbagi data ancaman).",
        "2. Donor Bantuan Utama: AS (Ke Israel/Ukraina), China (Ke Afrika/Asia), Uni Eropa (Ke Balkan).",
        "3. Operasi Sabotase: Mossad (Israel), FSB (Rusia), CIA (AS), MSS (China)."
    ],
    "fokus_geopolitik_indonesia__the_balancer_": [
        "[FOKUS GEOPOLITIK INDONESIA (THE BALANCER)]",
        "1. Diplomasi Bebas Aktif: Mampu menjadi mediator konflik P5 tanpa sanksi.",
        "2. Isu Laut Natuna Utara: Ketegangan ZEE dengan China (Sikap: Tegas/Waspada).",
        "3. Kepemimpinan ASEAN: Penggerak utama stabilitas Asia Tenggara.",
        "4. Solidaritas Palestina: Dukungan diplomatik mutlak di PBB."
    ],
    "soft_power___hegemoni_teknologi__cultural_war_": [
        "[SOFT POWER & HEGEMONI TEKNOLOGI (CULTURAL WAR)]",
        "1. Ekspor Budaya: Korea Selatan (K-Pop), Jepang (Anime), AS (Hollywood).",
        "2. Perang Chip AI & Semikonduktor: AS vs China (Menentukan efisiensi industri).",
        "3. Diplomasi Olahraga: Arab Saudi/Qatar (Investasi besar di sepakbola global)."
    ],
    "geopolitik_lingkungan___digital__emerging_threats_": [
        "[GEOPOLITIK LINGKUNGAN & DIGITAL (EMERGING THREATS)]",
        "1. Krisis Air: Mesir vs Ethiopia (Nil), India vs Pakistan (Indus).",
        "2. Ancaman Kenaikan Air Laut: Tuvalu, Maladewa, Kiribati (Negara Terancam Hilang).",
        "3. Infrastruktur Digital: Sabotase kabel internet bawah laut (Selat Malaka/Pasifik)."
    ],
    "hukum_internasional___perang_informasi__legal___info_war_": [
        "[HUKUM INTERNASIONAL & PERANG INFORMASI (LEGAL & INFO WAR)]",
        "1. Peradilan Internasional (ICC/ICJ): Penuntutan penjahat perang (Merusak Reputasi).",
        "2. Kampanye Disinformasi: Penggunaan Bot Medsos untuk mengacaukan opini publik lawan.",
        "3. Kerahasiaan Perbankan (Tax Havens): Swiss, Panama, Cayman Islands (Aset Tersembunyi)."
    ],
    "diplomasi_agama___identitas__identity_blocs_": [
        "[DIPLOMASI AGAMA & IDENTITAS (IDENTITY BLOCS)]",
        "1. Organisasi Kerjasama Islam (OKI): Solidaritas Indonesia, Saudi, Turki, dll.",
        "2. Pengaruh Moral Vatikan: Mempengaruhi kebijakan negara-negara Katolik.",
        "3. Aliansi Ortodoks: Ikatan Rusia, Serbia, dan Yunani."
    ],
    "migrasi___diplomasi_kesehatan__human_capital_": [
        "[MIGRASI & DIPLOMASI KESEHATAN (HUMAN CAPITAL)]",
        "1. Weaponized Migration: Menggunakan arus pengungsi untuk menekan lawan politik.",
        "2. Diplomasi Vaksin/Medis: China, AS, Rusia (Pengaruh lewat bantuan kesehatan).",
        "3. Brain Drain: Perpindahan tenaga ahli dari negara berkembang ke negara maju."
    ],
    "aktor_non-negara___ancaman_transnasional__non-state_actors_": [
        "[AKTOR NON-NEGARA & ANCAMAN TRANSNASIONAL (NON-STATE ACTORS)]",
        "1. Tentara Bayaran (PMC): Wagner Group (Rusia), Blackwater (AS).",
        "2. Kartel Narkoba: Mempengaruhi stabilitas Meksiko, Kolombia, & Amerika Latin.",
        "3. Kelompok Teroris: Ancaman asimetris yang memaksa intervensi global."
    ],
    "geopolitik_keuangan___digital__financial_warfare_": [
        "[GEOPOLITIK KEUANGAN & DIGITAL (FINANCIAL WARFARE)]",
        "1. Kontrol SWIFT (AS): Mampu memutus akses finansial negara manapun.",
        "2. De-dollarisasi: Upaya China, Rusia, & Brazil mengurangi ketergantungan Dolar.",
        "3. Kedaulatan Digital (Tembok Api): China (Great Firewall), Rusia (RuNet)."
    ],
    "ketahanan_pangan___transisi_energi__future_survival_": [
        "[KETAHANAN PANGAN & TRANSISI ENERGI (FUTURE SURVIVAL)]",
        "1. Senjata Gandum & Pupuk: Rusia & Ukraina (Mempengaruhi kelaparan global).",
        "2. Perebutan Logam Hijau: Kongo (Cobalt) & Amerika Latin (Lithium).",
        "3. Kemandirian Pangan: Faktor kunci kedaulatan negara (Bisa di-embargo)."
    ],
    "tata_dunia_baru__multipolarity_": [
        "[TATA DUNIA BARU (MULTIPOLARITY)]",
        "1. Kebangkitan Global South: Indonesia, India, Brazil (Menolak Blok Barat/Timur).",
        "2. Jebakan Utang (Debt Trap): Pengaruh China lewat infrastruktur di negara berkembang.",
        "3. Aliansi Fleksibel: Negara yang berpindah blok sesuai keuntungan ekonomi harian."
    ],
    "frontier_terakhir__the_last_battlegrounds_": [
        "[FRONTIER TERAKHIR (THE LAST BATTLEGROUNDS)]",
        "1. Perang Algoritma: Mempengaruhi opini publik global lewat kontrol platform digital.",
        "2. Status Antartika: Klaim wilayah masa depan untuk mineral & air tawar.",
        "3. Perlombaan AGI: Dominasi teknologi total yang bisa mematikan semua sanksi."
    ],
    "ekonomi_biru___keamanan_maritim__maritime_sovereignty_": [
        "[EKONOMI BIRU & KEAMANAN MARITIM (MARITIME SOVEREIGNTY)]",
        "1. Pencurian Ikan (Illegal Fishing): Sengketa ZEE dengan armada nelayan asing.",
        "2. Penambangan Laut Dalam: Perebutan mineral di dasar samudera internasional.",
        "3. Perlindungan ZEE: Faktor kunci kedaulatan negara kepulauan (Indonesia/Filipina)."
    ],
    "risiko_eksistensial__global_threats_": [
        "[RISIKO EKSISTENSIAL (GLOBAL THREATS)]",
        "1. Kessler Syndrome: Hancurnya satelit global yang mematikan fitur GPS/Digital.",
        "2. Senjata ASAT: Kemampuan menghancurkan satelit musuh di orbit.",
        "3. Pertahanan Planet (NEO): Keharusan bersatu melawan ancaman asteroid."
    ],
    "infrastruktur_kritis__systemic_vulnerability_": [
        "[INFRASTRUKTUR KRITIS (SYSTEMIC VULNERABILITY)]",
        "1. Sabotase Listrik: Blackout massal yang mematikan industri & ekonomi.",
        "2. Serangan Kilang Minyak: Drone/Sabotase yang memicu lonjakan harga BBM.",
        "3. Terorisme Finansial: Virus perbankan yang menghancurkan kepercayaan pasar."
    ],
    "bio-keamanan___pandemi__biological_threats_": [
        "[BIO-KEAMANAN & PANDEMI (BIOLOGICAL THREATS)]",
        "1. Bio-Terorisme: Penggunaan patogen sebagai senjata pemusnah massal.",
        "2. Kebocoran Lab: Pemicu krisis diplomatik & tuduhan internasional.",
        "3. Nasionalisme Vaksin: Monopoli obat-obatan yang memecah blok dunia."
    ],
    "ham___reputasi_moral__moral_diplomacy_": [
        "[HAM & REPUTASI MORAL (MORAL DIPLOMACY)]",
        "1. Sanksi HAM: Pengucilan ekonomi atas dasar isu kemanusiaan.",
        "2. Boikot Internasional: Penurunan skor ekonomi akibat tekanan opini publik.",
        "3. Kampanye LSM Global: Tekanan dari organisasi non-pemerintah (NGO)."
    ],
    "warisan_budaya___wisata__cultural_mobility_": [
        "[WARISAN BUDAYA & WISATA (CULTURAL MOBILITY)]",
        "1. Repatriasi Artefak: Pengembalian benda sejarah (Meningkatkan Harga Diri).",
        "2. Diplomasi Visa: Bebas Visa vs Travel Ban (Simbol persahabatan/permusuhan).",
        "3. Senjata Turis: Pemutusan arus wisatawan untuk menekan ekonomi lawan."
    ],
    "kripto___dinamika_demografi__future_shifts_": [
        "[KRIPTO & DINAMIKA DEMOGRAFI (FUTURE SHIFTS)]",
        "1. Crypto-Diplomacy: Penggunaan aset digital untuk menembus sanksi ekonomi.",
        "2. Bonus vs Krisis Demografi: Pertumbuhan Afrika/ASEAN vs Penuaan Eropa/Jepang.",
        "3. Hegemoni Bahasa: Penyebaran bahasa sebagai alat kontrol Soft Power."
    ],
    "ideologi___kedaulatan_data__value_war_": [
        "[IDEOLOGI & KEDAULATAN DATA (VALUE WAR)]",
        "1. Liberalisme vs Otoriter: Pertentangan nilai dasar dalam diplomasi.",
        "2. Lokalisasi Data: Kewajiban penyimpanan data di dalam negeri (Sovereignty).",
        "3. Ekspor Teknologi Pengawasan: Pengaruh politik lewat kontrol keamanan digital."
    ],
    "geopolitik_energi_nuklir__nuclear_power_": [
        "[GEOPOLITIK ENERGI NUKLIR (NUCLEAR POWER)]",
        "1. Pasokan Uranium: Kazakhstan, Kanada, Australia (Kunci energi masa depan).",
        "2. Keamanan PLTN di Wilayah Perang: Risiko kebocoran radiasi massal.",
        "3. Aliansi Teknologi Nuklir: Transfer ilmu pengetahuan untuk pengaruh politik."
    ],
    "separatisme___stabilitas__internal_sovereignty_": [
        "[SEPARATISME & STABILITAS (INTERNAL SOVEREIGNTY)]",
        "1. Gerakan Separatisme: Ancaman disintegrasi wilayah (Skotlandia, Catalonia, dll).",
        "2. Dukungan Proxy ke Pemberontak: Negara rival mendanai separatis lawan.",
        "3. Integritas Teritorial: Fokus utama kedaulatan (Indonesia, Spanyol, Inggris)."
    ],
    "ai___senjata_otonom__the_silicon_war_": [
        "[AI & SENJATA OTONOM (THE SILICON WAR)]",
        "1. Lethal Autonomous Weapons (LAWs): Robot pembunuh tanpa kendali manusia.",
        "2. Standar Keamanan AI Global: Upaya PBB meregulasi kecerdasan buatan.",
        "3. Kedaulatan Algoritma: Perlindungan infrastruktur digital dari sabotase AI."
    ],
    "paten___supremasi_maritim__the_global_chessboard_": [
        "[PATEN & SUPREMASI MARITIM (THE GLOBAL CHESSBOARD)]",
        "1. Perang Paten: Monopoli teknologi untuk mematikan industri kompetitor.",
        "2. String of Pearls: Pangkalan China di Samudera Hindia (Pengepungan India).",
        "3. Diplomasi Kapal Perang: Penggunaan kapal induk untuk tekanan psikologis."
    ],
    "masa_depan_ekstrim__the_next_frontier_": [
        "[MASA DEPAN EKSTRIM (THE NEXT FRONTIER)]",
        "1. Penambangan Bulan: Helium-3 sebagai pengganti minyak (Kiamat ekonomi OPEC).",
        "2. Perang Nilai Global: Konservatif vs Liberal (Pertentangan budaya total).",
        "3. Riset Keabadian: Penguasaan teknologi kesehatan untuk menarik elit global."
    ],
    "era_kuantum___rekayasa_manusia__the_ultimate_shifts_": [
        "[ERA KUANTUM & REKAYASA MANUSIA (THE ULTIMATE SHIFTS)]",
        "1. Quantum Supremacy: Kemampuan membongkar seluruh enkripsi keamanan dunia.",
        "2. Diplomasi UBI: Model negara ideal yang memicu revolusi di negara tetangga.",
        "3. Etika Genetika: Modifikasi populasi (Unggul secara fisik tapi dikucilkan moral)."
    ],
    "adaptasi_ekstrim__survival_technologies_": [
        "[ADAPTASI EKSTRIM (SURVIVAL TECHNOLOGIES)]",
        "1. Kota Terapung: Kedaulatan baru di laut internasional (Adaptasi tenggelam).",
        "2. Monopoli Desalinasi: Kontrol air tawar global (Senjata diplomatik baru).",
        "3. Pertanian Vertikal: Kemandirian pangan mutlak yang kebal embargo."
    ],
    "manipulasi_dunia__radikal_shifts_": [
        "[MANIPULASI DUNIA (RADIKAL SHIFTS)]",
        "1. Geo-Engineering: Manipulasi cuaca sepihak yang merusak iklim negara tetangga.",
        "2. Transparansi Radikal: Kebocoran rahasia negara masal (Menghancurkan stabilitas).",
        "3. AI Legal Status: AI sebagai entitas hukum yang memiliki hak suara di PBB."
    ],
    "dinasti___kekuatan_elit__inner_circle_": [
        "[DINASTI & KEKUATAN ELIT (INNER CIRCLE)]",
        "1. Dinasti Politik: Stabilitas kebijakan jangka panjang vs Isu Nepotisme.",
        "2. Oligarki Korporasi: Kebijakan luar negeri yang didikte oleh profit industri.",
        "3. Filantropi Strategis: Pengaruh global lewat bantuan non-pemerintah."
    ],
    "sains___standar_digital__tech_sovereignty_": [
        "[SAINS & STANDAR DIGITAL (TECH SOVEREIGNTY)]",
        "1. Mandat Open Source: Kemandirian dari ketergantungan vendor asing (Microsoft/Google).",
        "2. Diplomasi Nobel: Prestise intelektual sebagai daya tawar diplomasi.",
        "3. Perang Protokol: Persaingan standar teknis global (5G/6G/Digital Currency)."
    ],
    "konservasi___satwa__wildlife_diplomacy_": [
        "[KONSERVASI & SATWA (WILDLIFE DIPLOMACY)]",
        "1. Sengketa Perburuan Paus: Jepang/Norwegia vs Komunitas Internasional.",
        "2. Diplomasi Panda: Penggunaan peminjaman satwa sebagai simbol aliansi (China).",
        "3. Sanksi Perdagangan Satwa: Tekanan terhadap pasar gading/cula ilegal."
    ],
    "nilai_sosial___hak_individu__cultural_values_": [
        "[NILAI SOSIAL & HAK INDIVIDU (CULTURAL VALUES)]",
        "1. Hak LGBTQ+: Pertentangan nilai antara Blok Liberal vs Konservatif.",
        "2. Indeks Kebahagiaan: Faktor penarik migrasi elit & tenaga ahli global.",
        "3. Kesetaraan Gender: Syarat kepemimpinan di organisasi internasional."
    ],
    "revisi_sejarah___narasi__historical_conflicts_": [
        "[REVISI SEJARAH & NARASI (HISTORICAL CONFLICTS)]",
        "1. Sengketa Buku Sejarah: Narasi masa lalu yang memicu kemarahan tetangga.",
        "2. Penyangkalan Tragedi: Isu sensitif yang bisa membekukan hubungan selamanya.",
        "3. Perang Monumen: Pendirian/penghancuran simbol sejarah yang memicu protes."
    ],
    "iklim___keadilan_global__green_diplomacy_": [
        "[IKLIM & KEADILAN GLOBAL (GREEN DIPLOMACY)]",
        "1. Climate Denial vs Action: Hambatan kebijakan hijau demi ekonomi fosil.",
        "2. Pajak Karbon Lintas Batas: Konflik dagang atas dasar standar emisi.",
        "3. Keadilan Iklim: Tuntutan kompensasi dari negara berkembang ke negara maju."
    ],
    "populisme___perang_info__internal_dynamics_": [
        "[POPULISME & PERANG INFO (INTERNAL DYNAMICS)]",
        "1. Kepemimpinan Populis: Kebijakan nasionalis yang menarik diri dari forum global.",
        "2. Kebebasan Pers: Reputasi negara yang mempengaruhi bantuan finansial global.",
        "3. Propaganda Media Internasional: Penggunaan media untuk narasi Soft Power."
    ],
    "hukum___kejahatan_transnasional__global_justice_": [
        "[HUKUM & KEJAHATAN TRANSNASIONAL (GLOBAL JUSTICE)]",
        "1. War on Drugs: Operasi militer lintas batas melawan kartel narkoba.",
        "2. Hukuman Mati: Perbedaan standar hukum yang menghambat ekstradisi.",
        "3. Anti-Money Laundering: Blacklist finansial bagi negara yang melindungi uang gelap."
    ],
    "pendidikan___kota_pintar__future_influence_": [
        "[PENDIDIKAN & KOTA PINTAR (FUTURE INFLUENCE)]",
        "1. Diplomasi Kampus: Ekspor sistem pendidikan & nilai budaya ke elit asing.",
        "2. Smart City Hegemony: Kontrol data lewat pembangunan infrastruktur kota digital.",
        "3. Standar Siber Nasional: Ekspor hukum internet (GDPR/Firewall) ke negara mitra."
    ],
    "kedaulatan_frontier__strategic_outposts_": [
        "[KEDAULATAN FRONTIER (STRATEGIC OUTPOSTS)]",
        "1. Sengketa Pulau Terpencil: Penggunaan pulau sebagai pangkalan militer rahasia.",
        "2. Slot Orbit Satelit: Perebutan kapasitas orbit untuk komunikasi global.",
        "3. Zona Pertahanan Udara (ADIZ): Provokasi lewat tumpang tindih wilayah udara."
    ],
    "korupsi___lobbying_global__the_dark_money_": [
        "[KORUPSI & LOBBYING GLOBAL (THE DARK MONEY)]",
        "1. Sportswashing: Menjadi tuan rumah event besar demi reputasi moral.",
        "2. Kleptokrasi: Pencucian uang hasil korupsi pemimpin di bank asing.",
        "3. Lobbying Internasional: Membayar agen asing untuk mempengaruhi kebijakan lawan."
    ],
    "utang___lembaga_global__financial_hegemony_": [
        "[UTANG & LEMBAGA GLOBAL (FINANCIAL HEGEMONY)]",
        "1. Debt Trap Diplomacy: Pemberian pinjaman untuk menguasai aset strategis lawan.",
        "2. Syarat IMF/World Bank: Bantuan finansial yang mengikat kebijakan internal.",
        "3. Credit Rating Hegemony: Pengaruh lembaga rating Barat terhadap ekonomi global."
    ],
    "demografi_tua___krisis_pensiun__aging_crisis_": [
        "[DEMOGRAFI TUA & KRISIS PENSIUN (AGING CRISIS)]",
        "1. Krisis Dana Pensiun: Beban anggaran lansia yang memangkas biaya militer.",
        "2. Kebutuhan Imigrasi: Dilema antara kebutuhan buruh vs stabilitas budaya.",
        "3. Robotik Lansia: Solusi teknologi untuk menambal kekurangan tenaga kerja."
    ],
    "produktivitas___kesehatan_mental__human_capital_": [
        "[PRODUKTIVITAS & KESEHATAN MENTAL (HUMAN CAPITAL)]",
        "1. Krisis Kebahagiaan: Penurunan produktivitas & angka kelahiran (Jepang/Korea).",
        "2. Daya Tarik Migrasi Elit: Negara bahagia sebagai magnet talenta global.",
        "3. Sabotase Budaya Digital: Adiksi platform asing yang menurunkan fokus SDM."
    ],
    "kepercayaan___legitimasi__global_authority_": [
        "[KEPERCAYAAN & LEGITIMASI (GLOBAL AUTHORITY)]",
        "1. Legitimasi PBB: Menentukan apakah resolusi akan dipatuhi atau diabaikan.",
        "2. Trust in Government: Ketahanan terhadap infiltrasi ideologi & kudeta.",
        "3. Diplomasi Transparansi: Membuka data negara untuk menarik investor global."
    ],
    "buruh___pangan_global__social_standards_": [
        "[BURUH & PANGAN GLOBAL (SOCIAL STANDARDS)]",
        "1. Sanksi Buruh: Tekanan standar keselamatan & pekerja anak terhadap industri.",
        "2. Perang Pangan GMO: Larangan produk rekayasa genetika (Eropa vs AS/Brazil).",
        "3. Perlindungan Pekerja Migran: Isu sensitif antara negara pengirim vs penerima."
    ],
    "suaka___fragmentasi__global_governance_": [
        "[SUAKA & FRAGMENTASI (GLOBAL GOVERNANCE)]",
        "1. Suaka Politik: Melindungi buronan politik lawan (Pemicu krisis diplomatik).",
        "2. The Splinternet: Fragmentasi internet global menjadi blok-blok nasional.",
        "3. Kontrol Lembaga Dunia: Persaingan posisi kunci di WHO, Interpol, & UNESCO."
    ],
    "energi___pengawasan__modern_warfare_": [
        "[ENERGI & PENGAWASAN (MODERN WARFARE)]",
        "1. Shale Gas & Fracking: Kemandirian energi yang merusak dominasi OPEC.",
        "2. Mass Surveillance: Pengawasan warga demi stabilitas vs Tekanan HAM.",
        "3. Diplomasi Drone: Penggunaan teknologi nirawak untuk menekan lawan."
    ],
    "strategi_indonesia__the_indonesia_way_": [
        "[STRATEGI INDONESIA (THE INDONESIA WAY)]",
        "1. Hilirisasi Industri: Pelarangan ekspor mentah (Nikel/Bauksit) untuk industri dalam negeri.",
        "2. Ibu Kota Nusantara (IKN): Pemindahan pusat kekuasaan ke jantung ekonomi baru.",
        "3. Poros Maritim Dunia: Penguasaan jalur perdagangan laut antar samudera."
    ],
    "soft_power_indonesia__national_prestige_": [
        "[SOFT POWER INDONESIA (NATIONAL PRESTIGE)]",
        "1. Moderasi Beragama: Model toleransi yang diakui dunia (Prestise Moral).",
        "2. Global Halal Hub: Standarisasi industri halal bagi pasar muslim dunia.",
        "3. Bonus Demografi: Kekuatan konsumsi & inovasi digital dari generasi muda."
    ],
    "stabilitas___kepemimpinan__regional_authority_": [
        "[STABILITAS & KEPEMIMPINAN (REGIONAL AUTHORITY)]",
        "1. ASEAN Centrality: Indonesia sebagai pengarah kebijakan utama di Asia Tenggara.",
        "2. Integritas Papua: Ketahanan terhadap tekanan internasional terkait isu separatisme.",
        "3. Kedaulatan Natuna: Pertahanan fisik & diplomatik di wilayah sengketa maritim."
    ],
    "bencana___kemanusiaan__disaster_diplomacy_": [
        "[BENCANA & KEMANUSIAAN (DISASTER DIPLOMACY)]",
        "1. Bantuan Tragedi: Perbaikan hubungan instan lewat bantuan bencana alam.",
        "2. Koridor Kemanusiaan: Prestise moral bagi negara yang memfasilitasi bantuan.",
        "3. Solidaritas Global: Momen langka kerjasama antar musuh saat terjadi kiamat kecil."
    ],
    "logistik___infrastruktur__global_flow_": [
        "[LOGISTIK & INFRASTRUKTUR (GLOBAL FLOW)]",
        "1. Chokepoints Maritim: Suez, Panama, Malaka (Titik nadi ekonomi dunia).",
        "2. Backbone Digital: Keamanan kabel internet bawah laut lintas samudera.",
        "3. Kontrol Pelabuhan: Dominasi logistik lewat pusat transhipment global."
    ],
    "globalisme_vs_nasionalisme__the_great_divide_": [
        "[GLOBALISME VS NASIONALISME (THE GREAT DIVIDE)]",
        "1. Integrasi Global: Dunia tanpa batas vs Proteksionisme nasional.",
        "2. Forum G7 vs BRICS+: Persaingan menentukan standar ekonomi dunia.",
        "3. Kedaulatan Mutlak: Penolakan terhadap intervensi lembaga internasional."
    ],
    "budaya___kebebasan__cultural_sovereignty_": [
        "[BUDAYA & KEBEBASAN (CULTURAL SOVEREIGNTY)]",
        "1. Diplomasi Medis Tradisional: Promosi TCM/Herbal sebagai Soft Power (China/India).",
        "2. Ekspresi vs Penistaan: Konflik nilai kebebasan bicara vs perlindungan agama.",
        "3. Sensor Konten Digital: Kedaulatan negara dalam mengatur informasi di internet."
    ],
    "satelit___kedaulatan__private_space_age_": [
        "[SATELIT & KEDAULATAN (PRIVATE SPACE AGE)]",
        "1. Konstelasi Satelit Swasta: Internet global yang sulit dikontrol negara (Starlink).",
        "2. Spionase Swasta: Penjualan citra satelit resolusi tinggi ke pihak non-pemerintah.",
        "3. Logistik Roket: Penggunaan wilayah strategis (Biak/Equator) sebagai pusat peluncuran."
    ],
    "limbah___transparansi__environmental_secrets_": [
        "[LIMBAH & TRANSPARANSI (ENVIRONMENTAL SECRETS)]",
        "1. Diplomasi Limbah: Ekspor sampah plastik/elektronik ke negara berkembang.",
        "2. Penampungan Limbah Nuklir: Kompensasi ekonomi tinggi vs Isolasi diplomatik.",
        "3. Transparansi Anggaran: Skor kejujuran negara yang menentukan akses dana hibah."
    ],
    "teknologi_futuristik__beyond_earth_": [
        "[TEKNOLOGI FUTURISTIK (BEYOND EARTH)]",
        "1. Space-Based Solar Power: Transmisi energi dari orbit (Energi tanpa batas).",
        "2. Metaverse Sovereignty: Kedaulatan hukum & pajak di dunia virtual global.",
        "3. Diplomasi Avatar: Pertemuan diplomatik rahasia di ruang virtual terenkripsi."
    ],
    "logika_drift_otomatis__ai_to_ai_": [
        "[LOGIKA DRIFT OTOMATIS (AI TO AI)]",
        "Logika ini akan diletakkan di `DrifterHubungan.ts` dan akan berjalan setiap hari (In-game):",
        "1. RIVALRY LOOP:",
        "   Jika (Negara A & Negara B) ada di daftar [HOTSPOTS], maka Skor Hubungan mereka akan otomatis TURUN 0.1 - 0.5 poin setiap hari secara alami, kecuali ada Player yang mendamaikan.",
        "2. ALLIANCE SHIELD:",
        "   Jika (Negara A & Negara B) ada di daftar [BLOK BARAT], maka Skor Hubungan mereka akan otomatis NAIK atau bertahan di level tinggi (+0.1 per hari).",
        "3. DOMINO EFFECT:",
        "   Jika Player menyerang Negara A, maka semua teman Negara A (dalam Blok yang sama) akan otomatis membenci Player sebesar 50% dari efek aslinya."
    ]
};
