import { countries } from "@/app/database/data/countries/region/index";

export type UNGroup = "African Group" | "Asia-Pacific Group" | "Eastern European Group" | "GRULAC" | "WEOG";

export const UN_GROUPS_CONFIG: Record<UNGroup, { seats: number }> = {
  "African Group": { seats: 3 },
  "Asia-Pacific Group": { seats: 2 },
  "Eastern European Group": { seats: 1 },
  "GRULAC": { seats: 2 },
  "WEOG": { seats: 2 },
};

// ══════════════════════════════════════════
// EXPLICIT MAPPING: 207 Countries → UN Group
// Based on: c:\fhm\EM\daftar-menu\7.DAFTAR NEGARA.txt
// ══════════════════════════════════════════

const UN_GROUP_MAP: Record<string, UNGroup> = {
  // ── AFRICAN GROUP (54 negara) ──
  "afrika selatan": "African Group",
  "aljazair": "African Group",
  "angola": "African Group",
  "benin": "African Group",
  "botswana": "African Group",
  "burkina faso": "African Group",
  "burundi": "African Group",
  "chad": "African Group",
  "djibouti": "African Group",
  "eritrea": "African Group",
  "eswatini": "African Group",
  "ethiopia": "African Group",
  "gabon": "African Group",
  "gambia": "African Group",
  "ghana": "African Group",
  "guinea": "African Group",
  "guinea bissau": "African Group",
  "kamerun": "African Group",
  "kenya": "African Group",
  "komoro": "African Group",
  "kongo": "African Group",
  "lesotho": "African Group",
  "liberia": "African Group",
  "libya": "African Group",
  "madagaskar": "African Group",
  "malawi": "African Group",
  "mali": "African Group",
  "maroko": "African Group",
  "mauritania": "African Group",
  "mauritius": "African Group",
  "mesir": "African Group",
  "mozambik": "African Group",
  "namibia": "African Group",
  "niger": "African Group",
  "nigeria": "African Group",
  "pantai gading": "African Group",
  "republik afrika tengah": "African Group",
  "republik demokratik kongo": "African Group",
  "republik sudan": "African Group",
  "republik tanzania": "African Group",
  "republik uganda": "African Group",
  "republik zambia": "African Group",
  "republik zimbabwe": "African Group",
  "rwanda": "African Group",
  "sao tome dan principe": "African Group",
  "senegal": "African Group",
  "seychelles": "African Group",
  "sierra leone": "African Group",
  "somalia": "African Group",
  "sudan selatan": "African Group",
  "tanjung verde": "African Group",
  "togo": "African Group",
  "tunisia": "African Group",

  // ── ASIA-PACIFIC GROUP (53 negara) ──
  "afganistan": "Asia-Pacific Group",
  "arab saudi": "Asia-Pacific Group",
  "bahrain": "Asia-Pacific Group",
  "bangladesh": "Asia-Pacific Group",
  "bhutan": "Asia-Pacific Group",
  "brunei": "Asia-Pacific Group",
  "china": "Asia-Pacific Group",
  "fiji": "Asia-Pacific Group",
  "filipina": "Asia-Pacific Group",
  "hong kong": "Asia-Pacific Group",
  "india": "Asia-Pacific Group",
  "indonesia": "Asia-Pacific Group",
  "irak": "Asia-Pacific Group",
  "iran": "Asia-Pacific Group",
  "jepang": "Asia-Pacific Group",
  "kamboja": "Asia-Pacific Group",
  "kazakhstan": "Asia-Pacific Group",
  "kirgizstan": "Asia-Pacific Group",
  "kiribati": "Asia-Pacific Group",
  "korea selatan": "Asia-Pacific Group",
  "korea utara": "Asia-Pacific Group",
  "kuwait": "Asia-Pacific Group",
  "laos": "Asia-Pacific Group",
  "lebanon": "Asia-Pacific Group",
  "makau": "Asia-Pacific Group",
  "malaysia": "Asia-Pacific Group",
  "maldives": "Asia-Pacific Group",
  "marshall": "Asia-Pacific Group",
  "mikronesia": "Asia-Pacific Group",
  "mongolia": "Asia-Pacific Group",
  "myanmar": "Asia-Pacific Group",
  "nauru": "Asia-Pacific Group",
  "nepal": "Asia-Pacific Group",
  "oman": "Asia-Pacific Group",
  "pakistan": "Asia-Pacific Group",
  "palau": "Asia-Pacific Group",
  "palestina": "Asia-Pacific Group",
  "papua nugini": "Asia-Pacific Group",
  "qatar": "Asia-Pacific Group",
  "republik timor leste": "Asia-Pacific Group",
  "samoa": "Asia-Pacific Group",
  "samoa amerika": "Asia-Pacific Group",
  "singapura": "Asia-Pacific Group",
  "sri lanka": "Asia-Pacific Group",
  "suriah": "Asia-Pacific Group",
  "tahiti": "Asia-Pacific Group",
  "taiwan": "Asia-Pacific Group",
  "tajikistan": "Asia-Pacific Group",
  "thailand": "Asia-Pacific Group",
  "tonga": "Asia-Pacific Group",
  "turkmenistan": "Asia-Pacific Group",
  "tuvalu": "Asia-Pacific Group",
  "uni emirat arab": "Asia-Pacific Group",
  "uzbekistan": "Asia-Pacific Group",
  "vanuatu": "Asia-Pacific Group",
  "vietnam": "Asia-Pacific Group",
  "yaman": "Asia-Pacific Group",
  "yordania": "Asia-Pacific Group",
  "guam": "Asia-Pacific Group",

  // ── EASTERN EUROPEAN GROUP (23 negara) ──
  "albania": "Eastern European Group",
  "armenia": "Eastern European Group",
  "azerbaijan": "Eastern European Group",
  "belarus": "Eastern European Group",
  "bosnia dan hercegovina": "Eastern European Group",
  "bulgaria": "Eastern European Group",
  "ceko": "Eastern European Group",
  "estonia": "Eastern European Group",
  "georgia": "Eastern European Group",
  "hungaria": "Eastern European Group",
  "kosovo": "Eastern European Group",
  "kroasia": "Eastern European Group",
  "latvia": "Eastern European Group",
  "lithuania": "Eastern European Group",
  "makedonia utara": "Eastern European Group",
  "moldova": "Eastern European Group",
  "montenegro": "Eastern European Group",
  "polandia": "Eastern European Group",
  "republik rumania": "Eastern European Group",
  "republik serbia": "Eastern European Group",
  "rusia": "Eastern European Group",
  "slowakia": "Eastern European Group",
  "slovenia": "Eastern European Group",
  "ukraina": "Eastern European Group",

  // ── GRULAC (Latin America & Caribbean - 33 negara) ──
  "antigua dan barbuda": "GRULAC",
  "argentina": "GRULAC",
  "bahama": "GRULAC",
  "barbados": "GRULAC",
  "belize": "GRULAC",
  "bermuda": "GRULAC",
  "bolivia": "GRULAC",
  "brazil": "GRULAC",
  "chile": "GRULAC",
  "costa rica": "GRULAC",
  "curacao": "GRULAC",
  "dominika": "GRULAC",
  "ekuador": "GRULAC",
  "el salvador": "GRULAC",
  "grenada": "GRULAC",
  "guatemala": "GRULAC",
  "guiana prancis": "GRULAC",
  "guyana": "GRULAC",
  "haiti": "GRULAC",
  "honduras": "GRULAC",
  "jamaika": "GRULAC",
  "kolombia": "GRULAC",
  "kuba": "GRULAC",
  "meksiko": "GRULAC",
  "nikaragua": "GRULAC",
  "panama": "GRULAC",
  "paraguay": "GRULAC",
  "peru": "GRULAC",
  "puerto rico": "GRULAC",
  "republik dominika": "GRULAC",
  "saint kitts dan nevis": "GRULAC",
  "saint lucia": "GRULAC",
  "saint vincent dan grenadine": "GRULAC",
  "suriname": "GRULAC",
  "trinidad dan tobago": "GRULAC",
  "uruguay": "GRULAC",
  "venezuela": "GRULAC",

  // ── WEOG (Western European & Others - 29 negara) ──
  "amerika serikat": "WEOG",
  "andorra": "WEOG",
  "australia": "WEOG",
  "austria": "WEOG",
  "belanda": "WEOG",
  "belgia": "WEOG",
  "denmark": "WEOG",
  "finlandia": "WEOG",
  "gibraltar": "WEOG",
  "greenland": "WEOG",
  "inggris": "WEOG",
  "irlandia": "WEOG",
  "islandia": "WEOG",
  "israel": "WEOG",
  "italia": "WEOG",
  "jerman": "WEOG",
  "kanada": "WEOG",
  "kepulauan faroe": "WEOG",
  "liechtenstein": "WEOG",
  "luksemburg": "WEOG",
  "malta": "WEOG",
  "monako": "WEOG",
  "norwegia": "WEOG",
  "portugal": "WEOG",
  "prancis": "WEOG",
  "san marino": "WEOG",
  "selandia baru": "WEOG",
  "siprus": "WEOG",
  "spanyol": "WEOG",
  "swedia": "WEOG",
  "swiss": "WEOG",
  "turki": "WEOG",
  "vatikan": "WEOG",
  "yunani": "WEOG",
};

export const getCountryUNGroup = (countryName: string): UNGroup => {
  const name = countryName.replace(/_/g, ' ').toLowerCase();
  return UN_GROUP_MAP[name] || "Asia-Pacific Group";
};

export const getCountriesByGroup = (group: UNGroup): string[] => {
  return countries
    .map(c => c.name_id)
    .filter(name => getCountryUNGroup(name) === group);
};
