export const komoditasPanganRate = {
  poultry_farm: {
    key: "poultry_farm",
    dataKey: "ayam_unggas",
    desc: "Peternakan Unggas",
    production: 1000,
    unit: "EKOR",
    maintenanceCost: 20,
    buildTime: 30,
    buildCost: 15,
    lowongan_kerja: 100
  },
  dairy_farm: {
    key: "dairy_farm",
    dataKey: "sapi_perah",
    desc: "Peternakan Sapi Perah",
    production: 500,
    unit: "LITER",
    maintenanceCost: 40,
    buildTime: 60,
    buildCost: 15,
    lowongan_kerja: 150
  },
  cattle_farm: {
    key: "cattle_farm",
    dataKey: "sapi_potong",
    desc: "Peternakan Sapi Potong",
    production: 100,
    unit: "EKOR",
    maintenanceCost: 60,
    buildTime: 90,
    buildCost: 15,
    lowongan_kerja: 120
  },
  sheep_farm: {
    key: "sheep_farm",
    dataKey: "domba_kambing",
    desc: "Peternakan Domba & Kambing",
    production: 200,
    unit: "EKOR",
    maintenanceCost: 30,
    buildTime: 60,
    buildCost: 15,
    lowongan_kerja: 80
  },
  shrimp_farm: {
    key: "shrimp_farm",
    dataKey: "udang_kerang",
    desc: "Tambak Udang Intensif",
    production: 1000,
    unit: "KG",
    maintenanceCost: 50,
    buildTime: 45,
    buildCost: 15,
    lowongan_kerja: 250
  },
  freshwater_fish_farm: {
    key: "freshwater_fish_farm",
    dataKey: "ikan",
    desc: "Budidaya Ikan Air Tawar",
    production: 2000,
    unit: "KG",
    maintenanceCost: 30,
    buildTime: 45,
    buildCost: 15,
    lowongan_kerja: 200
  },
  pearl_farm: {
    key: "pearl_farm",
    dataKey: "udang_kerang",
    desc: "Budidaya Kerang & Mutiara",
    production: 100,
    unit: "GRAM",
    maintenanceCost: 80,
    buildTime: 120,
    buildCost: 15,
    lowongan_kerja: 150
  },
  paddy_field: {
    key: "paddy_field",
    dataKey: "padi",
    desc: "Pertanian Padi",
    production: 5000,
    unit: "KG",
    maintenanceCost: 25,
    buildTime: 90,
    buildCost: 10,
    lowongan_kerja: 300
  },
  wheat_field: {
    key: "wheat_field",
    dataKey: "gandum_jagung",
    desc: "Pertanian Gandum",
    production: 3000,
    unit: "KG",
    maintenanceCost: 20,
    buildTime: 90,
    buildCost: 10,
    lowongan_kerja: 200
  },
  corn_field: {
    key: "corn_field",
    dataKey: "gandum_jagung",
    desc: "Pertanian Jagung",
    production: 4000,
    unit: "KG",
    maintenanceCost: 20,
    buildTime: 75,
    buildCost: 10,
    lowongan_kerja: 150
  },
  tuber_field: {
    key: "tuber_field",
    dataKey: "sayur_umbi",
    desc: "Pertanian Umbi-umbian",
    production: 6000,
    unit: "KG",
    maintenanceCost: 15,
    buildTime: 60,
    buildCost: 10,
    lowongan_kerja: 120
  },
  soybean_field: {
    key: "soybean_field",
    dataKey: "kedelai",
    desc: "Pertanian Kedelai",
    production: 2000,
    unit: "KG",
    maintenanceCost: 20,
    buildTime: 60,
    buildCost: 10,
    lowongan_kerja: 100
  },
  palm_oil_plantation: {
    key: "palm_oil_plantation",
    dataKey: "kelapa_sawit",
    desc: "Perkebunan Kelapa Sawit",
    production: 10000,
    unit: "LITER",
    maintenanceCost: 70,
    buildTime: 365,
    buildCost: 10,
    lowongan_kerja: 1000
  },
  tea_plantation: {
    key: "tea_plantation",
    dataKey: "kopi_teh_kakao",
    desc: "Perkebunan Teh",
    production: 500,
    unit: "KG",
    maintenanceCost: 30,
    buildTime: 180,
    buildCost: 10,
    lowongan_kerja: 400
  },
  coffee_plantation: {
    key: "coffee_plantation",
    dataKey: "kopi_teh_kakao",
    desc: "Perkebunan Kopi",
    production: 400,
    unit: "KG",
    maintenanceCost: 35,
    buildTime: 240,
    buildCost: 10,
    lowongan_kerja: 400
  },
  cocoa_plantation: {
    key: "cocoa_plantation",
    dataKey: "kopi_teh_kakao",
    desc: "Perkebunan Kakao",
    production: 300,
    unit: "KG",
    maintenanceCost: 40,
    buildTime: 300,
    buildCost: 10,
    lowongan_kerja: 400
  },
  sugarcane_plantation: {
    key: "sugarcane_plantation",
    dataKey: "tebu",
    desc: "Perkebunan Tebu",
    production: 5000,
    unit: "KG",
    maintenanceCost: 30,
    buildTime: 180,
    buildCost: 10,
    lowongan_kerja: 500
  },
  vegetable_farm: {
    key: "vegetable_farm",
    dataKey: "sayur_umbi",
    desc: "Pertanian Sayur Mayur",
    production: 2000,
    unit: "KG",
    maintenanceCost: 15,
    buildTime: 30,
    buildCost: 10,
    lowongan_kerja: 120
  }
};
